export const music = 
    [
        {
           "rank":1,
           "title":"내사람",
           "singer":"SG워너비",
           "poster":"https://musicmeta-phinf.pstatic.net/album/005/792/5792755.jpg?type=r360Fll&v=20230331131001",
           "state":"유지",
           "id":1,
           "key":"3cZrxpK2EAQ",
           "like":234867,
           "done":false,
           "album":"내사람 (Partner For Life)",
           "music_video":"https://www.youtube.com/embed/7lT1Wt41gDs"
        },
        {
           "rank":2,
           "title":"사랑 안해",
           "singer":"백지영",
           "poster":"https://musicmeta-phinf.pstatic.net/album/000/028/28202.jpg?type=r360Fll&v=20230307034223",
           "state":"상승",
           "id":2,
           "key":"v7bnOxV4jAc",
           "like":61326,
           "done":true,
           "album":"백지영 (사랑 안해)",
           "music_video":"https://www.youtube.com/embed/jN0uXBwKn8w"
        },
        {
           "rank":3,
           "title":"여인의 향기",
           "singer":"씨야",
           "poster":"https://musicmeta-phinf.pstatic.net/album/000/037/37647.jpg?type=r360Fll&v=20230307034210",
           "state":"상승",
           "id":3,
           "key":"ZHGhg7ewsDA",
           "like":87420,
           "done":false,
           "album":"씨야(SeeYa) 여인의 향기",
           "music_video":"https://www.youtube.com/embed/dDeoLLzpdMA"
        },
        {
           "rank":4,
           "title":"기다리다",
           "singer":"윤하",
           "poster":"https://musicmeta-phinf.pstatic.net/album/000/042/42956.jpg?type=r480Fll&v=20230331113336",
           "state":"상승",
           "id":4,
           "key":"0-q1KafFCLU",
           "like":271545,
           "done":false,
           "album":"윤하 (기다리다)",
           "music_video":"https://www.youtube.com/embed/LnSafu-mZqs"
        },
        {
           "rank":5,
           "title":"남자를 몰라",
           "singer":"버즈",
           "poster":"https://musicmeta-phinf.pstatic.net/album/000/039/39164.jpg?type=r360Fll&v=20230307034208",
           "state":"유지",
           "id":5,
           "key":"4HjcypoChfQ",
           "like":73823,
           "done":false,
           "album":"버즈 (남자를 몰라)",
           "music_video":"https://www.youtube.com/embed/6n6UZpv50AU"
        },
        {
           "rank":6,
           "title":"Love Me Love Me",
           "singer":"이지혜",
           "poster":"https://musicmeta-phinf.pstatic.net/album/000/465/465604.jpg?type=r480Fll&v=20230331120950",
           "state":"상승",
           "id":6,
           "key":"86BST8NIpNM",
           "like":73356,
           "done":false,
           "album":"Love Me Love Me (Remix)",
           "music_video":"https://www.youtube.com/embed/rq0PzCTlYWs"
        },
        {
           "rank":7,
           "title":"Hold The Line",
           "singer":"브라운아이드걸스",
           "poster":"https://musicmeta-phinf.pstatic.net/album/000/039/39681.jpg?type=r480Fll&v=20230331113319",
           "state":"상승",
           "id":7,
           "key":"VkLaZ7HEJ38",
           "like":133146,
           "done":false,
           "album":"Hold The Line (Feat. 조PD)",
           "music_video":"https://www.youtube.com/embed/FjoMFq6rVjg"
        },
        {
           "rank":8,
           "title":"까만안경",
           "singer":"이루",
           "poster":"https://musicmeta-phinf.pstatic.net/album/000/041/41442.jpg?type=r360Fll&v=20230307034204",
           "state":"하강",
           "id":8,
           "key":"CKZvWhCqx1s",
           "like":112292,
           "done":false,
           "album":"이루 까만안경 (Feat. Day Light)",
           "music_video":"https://www.youtube.com/embed/A9thrRZrA2c"
        },
        {
           "rank":9,
           "title":"내 여자라니까",
           "singer":"이승기",
           "poster":"https://musicmeta-phinf.pstatic.net/album/000/027/27843.jpg?type=r480Fll&v=20230307034224",
           "state":"하강",
           "id":9,
           "key":"iTu2ohlFVs0",
           "like":394328,
           "done":false,
           "album":"이승기 (내 여자라니까)",
           "music_video":"https://www.youtube.com/embed/vlDkOvXLgoY"
        },
        {
           "rank":10,
           "title":"그 남자 그 여자",
           "singer":"바이브",
           "poster":"https://musicmeta-phinf.pstatic.net/album/000/037/37769.jpg?type=r360Fll&v=20230307034210",
           "state":"유지",
           "id":10,
           "key":"gdZLi9oWNZg",
           "like":394328,
           "done":false,
           "album":"그 남자 그 여자 (Feat. 장혜진)",
           "music_video":"https://www.youtube.com/embed/Sv0FU_2I8eo"
        },
        {
           "rank":11,
           "title":"일년이면",
           "singer":"휘성(Realslow)",
           "poster":"https://musicmeta-phinf.pstatic.net/album/000/034/34498.jpg?type=r360Fll&v=20230307034214",
           "state":"유지",
           "id":11,
           "key":"7NTsVivHiZI",
           "like":22925,
           "done":false,
           "album":"휘성 (일년이면)",
           "music_video":"https://www.youtube.com/embed/BDbMLhh4gug"
        },
        {
           "rank":12,
           "title":"거리에서",
           "singer":"성시경",
           "poster":"https://musicmeta-phinf.pstatic.net/album/000/041/41669.jpg?type=r360Fll&v=20230307034204",
           "state":"유지",
           "id":12,
           "key":"pgMcZSseBaE",
           "like":143599,
           "done":false,
           "album":"성시경 (거리에서)",
           "music_video":"https://www.youtube.com/embed/qx4xDFP2WDU"
        },
        {
           "rank":13,
           "title":"밤하늘의 별을(2020)",
           "singer":"경서",
           "poster":"https://cdnimg.melon.co.kr/cm2/album/images/105/18/234/10518234_20210216102853_500.jpg/melon/resize/120/quality/80/optimize",
           "state":"유지",
           "id":13,
           "key":"bF26PVP84Dk",
           "like":131971,
           "done":false,
           "album":"밤하늘의 별을(2020)",
           "music_video":"https://www.youtube.com/embed/NuTNPV72rFo"
        },
        {
           "rank":14,
           "title":"가슴아 그만해",
           "singer":"엠씨더맥스",
           "poster":"https://musicmeta-phinf.pstatic.net/album/000/047/47455.jpg?type=r360Fll&v=20230307034156",
           "state":"유지",
           "id":14,
           "key":"D1PvIWdJ8xo",
           "like":301700,
           "done":false,
           "album":"엠씨더맥스(M.C the MAX) 가슴아 그만해",
           "music_video":"https://www.youtube.com/embed/uPj9xza-6Cs"
        },
        {
           "rank":15,
           "title":"톡!톡!톡! (Toc Toc Toc)",
           "singer":"이효리",
           "poster":"https://musicmeta-phinf.pstatic.net/album/000/144/144603.jpg?type=r100Fll&v=20230307033942",
           "state":"상승",
           "id":15,
           "key":"ZedH2Cj3GXQ",
           "like":57387,
           "done":false,
           "album":"이효리(톡!톡!톡!)",
           "music_video":"https://www.youtube.com/embed/7wX1sHvncFQ"
        },
        {
           "rank":16,
           "title":"사랑했나봐",
           "singer":"윤도현",
           "poster":"https://musicmeta-phinf.pstatic.net/album/000/032/32234.jpg?type=r360Fll&v=20230307034218",
           "state":"상승",
           "id":16,
           "key":"TgOu00Mf3kI",
           "like":353721,
           "done":false,
           "album":"윤도현 (사랑했나봐)'",
           "music_video":"https://www.youtube.com/embed/VwuP95CES70"
        },
     ]
